services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        HOST: 0.0.0.0
        PORT: 8000
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .data/pytest_cache:/app/.data/pytest_cache
      - .data/huggingface:/cache/huggingface
    environment:
      - DATASET_LANG=pt
      - DATASET_SIZE=200
      - WIKIPEDIA_DATES=20231101
      - MODEL_NAME=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - TOP_K_MAX=20
      - LEXICAL_CHAR_WEIGHT=0.4
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      - api
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - API_BASE=http://api:8000
