name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and dependencies
        run: |
          pip install uv
          cd api
          uv sync

      - name: Run tests
        run: pytest

  build-api:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build API Docker image
        run: |
          docker build -f api/Dockerfile -t letrus-api:ci .

  build-ui:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build UI Docker image
        run: |
          docker build -f ui/Dockerfile -t letrus-ui:ci .
