name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests
        env:
          USE_SAMPLE_DATA: "1"  # Keep CI fast and deterministic
        run: |
          pytest -q

      - name: Build Docker image
        run: |
          docker build -t letrus-plagiarism:ci .
